
export enum PLANOTYPES {
    SAUDE = 'SAUDE',
    VIAGEM = 'VIAGEM',
    AUTOMOVEL = 'AUTOMOVEL',
    ACIDENTETRABALHO = 'ACIDENTETRABALHO',
    RESPONSABILIDADE = 'RESPONSABILIDADE',
}

export enum PESSOAS{
    SINGULAR = "SINGULAR",
    COLETIVO = "COLETIVO",
}

export enum AUTHOPTIONS{
    SIGNIN = "SIGNIN",
    SIGNUP = "SIGNUP",
}
